### ISSUE TITLE
Definir a licença do projeto

### ISSUE THREAD

**Issue by lucasfcm9** [fga-eps-mds/2021.1-Pro-Especies-Docs#18]
## Descrição da Issue
Definir a licença do projeto.

- [x] Escolher qual será a licença para o projeto.

### Critérios de aceitação
- [x] Ter a licença bem definida e documentada no repositório.

**Comment by sudjoao** [comment]
A licença definida pelo grupo junto com o cliente foi a GNU AGPLv3
