### ISSUE TITLE
Refinar o Backlog do Produto

### ISSUE THREAD

**Issue by lucasfcm9** [fga-eps-mds/2021.1-Pro-Especies-Docs#54]
## Descrição da Issue
Realizar o refinamento do Backlog do Produto, ou seja, melhorar e deixar mais claro todas as atividades que serão realizadas.

### Tasks: 
- [x] Refinar o *backlog* do produto.

### Critérios de aceitação
- [x] Validar com a equipe.

**Comment by sudjoao** [comment]
Backlog V2
![BacklogV2](https://user-images.githubusercontent.com/46005310/131231040-fcf536a7-6e7c-4eee-9fc5-75d136065530.png)
