### ISSUE TITLE
E06US01 - Eu, como usuário, desejo editar ou remover dados do registro, a fim de aumentar a confiabilidade da coleta de dados

### ISSUE THREAD

**Issue by Neitan2001** [fga-eps-mds/2021.1-Pro-Especies-Docs#62]
## Descrição da Issue
Criação do método de edição de um registro e do método de deletar um registro.

#### Backend 
- [x] Criação do método de edição de um registro;
- [x] Criação do método de deletar um registro.

#### Frontend
- [x]  Criação da tela de edição de registro;
- [x]  Criação do botão de deleção de peixe.
- [x] Telas com estilização igual ao protótipo de alta fidelidade 

### Critérios de aceitação
- [x] Ser possível editar/remover um registro, como criador, se não estiver sido verificado ainda;
- [x] Ser possível editar o relatório como pesquisador;
- [x] Enviar um alerta de confirmação de exclusão antes de realizar.

**Comment by DanielCoimbra** [comment]
Finalizado.
